# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{drbqs}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Takayuki YAMAGUCHI"]
  s.date = %q{2011-03-01}
  s.description = %q{Task queuing system over network that is implemented by dRuby.}
  s.email = %q{d@ytak.info}
  s.executables = ["drbqs-node", "drbqs-server"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/drbqs-node",
    "bin/drbqs-server",
    "drbqs.gemspec",
    "lib/drbqs.rb",
    "lib/drbqs/acl_file.rb",
    "lib/drbqs/client.rb",
    "lib/drbqs/connection.rb",
    "lib/drbqs/message.rb",
    "lib/drbqs/queue.rb",
    "lib/drbqs/server.rb",
    "lib/drbqs/server_define.rb",
    "lib/drbqs/task_client.rb",
    "spec/acl_file_spec.rb",
    "spec/data/acl.txt",
    "spec/drbqs_spec.rb",
    "spec/server_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ytaka/drbqs}
  s.licenses = ["GPL3"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{dRuby Queueing System}
  s.test_files = [
    "spec/acl_file_spec.rb",
    "spec/drbqs_spec.rb",
    "spec/server_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

